# Generated by Django 2.0.7 on 2018-08-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_personalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='url',
            field=models.URLField(default='http://www.example.com'),
        ),
    ]
