# Generated by Django 2.1 on 2018-08-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_personalnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalnote',
            name='note_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.Note'),
        ),
    ]
