# Generated by Django 2.0.7 on 2018-07-31 17:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_peronalnote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeronalNote',
            new_name='PersonalNote',
        ),
    ]
