# Generated by Django 2.1 on 2018-08-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20180802_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.RemoveField(
            model_name='note',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.AddField(
            model_name='note',
            name='city',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='firstName',
            field=models.CharField(default='bob', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='lastName',
            field=models.CharField(default='barton', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='state',
            field=models.CharField(default='AR', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='zipCode',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
